### ISSUE TITLE
Error: Cannot find module 'core-js/modules/es7.string.pad-start'

### ISSUE THREAD

**Issue by okonet** [motiz88/git-exec-and-restage#6]
Just tried it in on my project and got this:

```
🚫 git-exec-and-restage prettier found some errors. Please fix them and try committing again.
module.js:471
    throw err;
    ^

Error: Cannot find module 'core-js/modules/es7.string.pad-start'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/okonet/Projects/feedly/client/node_modules/git-exec-and-restage/dist/polyfills.js:9:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

Any idea where it comes from? Looks like polyfills weren't installed?

**Comment by okonet** [comment]
This is what I got in `node_modules`:

```
➔ la node_modules/core-js/modules/es7.string.pad-
es7.string.pad-left.js   es7.string.pad-right.js
```

**Comment by motiz88** [comment]
@okonet That's weird. What versions of Node, npm etc are you using?

**Comment by okonet** [comment]
```
➔ node -v      
v6.10.2
```

Also latest npm 3.x

**Comment by motiz88** [comment]
Are you sure those are the exact filenames you're seeing? Here's the output on my machine (Node v6.9.4, npm 3.10.10) after a fresh install in a new package. 

```sh
$ ls -1 node_modules/core-js/modules/es7.string.pad-*
node_modules/core-js/modules/es7.string.pad-end.js
node_modules/core-js/modules/es7.string.pad-start.js
```

Also, I still can't reproduce the problem. If you can share a minimal reproducing setup in a Gist etc I'd be happy to look into it.

**Comment by okonet** [comment]
I'm traveling now. Will try to do when I get back. I'm using yarn on this project. Can this be related? Probably wrong version range?

**Comment by MoOx** [comment]
I am currently having the exact same problem.

❯ node --version
v8.1.3

❯ yarn --version
1.0.0

**Comment by MoOx** [comment]
I am actually having some deps (storybook) that require jscodeshift, that use babel-core ^5, that use core-js ^1 when almost all other use core-js 2^... That's the reason. So looks like a yarn issue in my case.

**Comment by okonet** [comment]
BTW my problems went away without doing anything so I think it's how yarn installs dependencies

**Comment by okonet** [comment]
So, it looks like it's not the yarn issue. I just switched to npm 5 and I'm seeing this behavior again after freshly installing all modules.

```sh
ls -1 node_modules/core-js/modules/es7.string.pad-*
node_modules/core-js/modules/es7.string.pad-left.js
node_modules/core-js/modules/es7.string.pad-right.js
```

So it looks like there is some version resolution conflict or the breaking change was introduced without following the SemVer in one of the babel/corejs projects.

**Comment by okonet** [comment]
Not sure if this is helpful but

```sh
cat package-lock.json | grep core-js
        "core-js": "2.5.1",
        "core-js": {
          "resolved": "https://registry.npmjs.org/core-js/-/core-js-2.5.1.tgz",
            "core-js": "2.5.1",
        "core-js": {
          "resolved": "https://registry.npmjs.org/core-js/-/core-js-2.5.1.tgz",
        "core-js": "2.5.1",
        "core-js": {
          "resolved": "https://registry.npmjs.org/core-js/-/core-js-2.5.1.tgz",
        "core-js": "2.5.1",
        "core-js": {
          "resolved": "https://registry.npmjs.org/core-js/-/core-js-2.5.1.tgz",
    "core-js": {
      "resolved": "https://registry.npmjs.org/core-js/-/core-js-1.2.7.tgz",
            "core-js": "1.2.7",
            "core-js": "1.2.7",
        "core-js": "1.2.7",
        "core-js": "1.2.7",
        "core-js": "2.5.1",
            "core-js": "2.5.1",
        "core-js": {
          "resolved": "https://registry.npmjs.org/core-js/-/core-js-2.5.1.tgz",
            "core-js": "1.2.7",
            "core-js": "1.2.7",
            "core-js": "1.2.7",
            "core-js": "1.2.7",
            "core-js": "1.2.7",
            "core-js": "1.2.7",
        "core-js": {
          "resolved": "https://registry.npmjs.org/core-js/-/core-js-2.5.1.tgz",
            "core-js": "2.5.1",
        "core-js": {
          "resolved": "https://registry.npmjs.org/core-js/-/core-js-2.5.1.tgz",
            "core-js": "2.5.1",
            "core-js": "1.2.7",
        "core-js": "2.5.1",
        "core-js": {
          "resolved": "https://registry.npmjs.org/core-js/-/core-js-2.5.1.tgz",
            "core-js": "1.2.7",
            "core-js": {
              "resolved": "https://registry.npmjs.org/core-js/-/core-js-1.2.7.tgz",
            "core-js": "1.2.7",
            "core-js": "1.2.7",
```

but I can't find anything with babel 5.x in there... 🤔

**Comment by bondib** [comment]
Delete your node modules folder. and run npm install again...

**Comment by okonet** [comment]
The error is consistent with the npm 5.x once you get there (removing `node_modules` doesn't help). What helps is to use yarn :shrug:

**Comment by frenic** [comment]
Adding `core-js` as devDependency worked for me.
